### ISSUE TITLE
Needs to be reclassified as a readme?

### ISSUE THREAD

**Issue by weezwo** [learn-co-curriculum/js-jquery-modify-html-readme#7]
This lesson is not a lab, but requires lab submission for completion.

<img width="2048" alt="screen shot 2017-04-27 at 3 01 38 pm" src="https://cloud.githubusercontent.com/assets/19954790/25499761/7f2ef96c-2b5a-11e7-9aeb-d56556f0ac0e.png">

**Comment by JessRudder** [comment]
Fixed!  Thanks!

**Comment by weezwo** [comment]
It seems as though nothing has changed. Is this something that would take a while to update?

**Comment by JessRudder** [comment]
@weezwo, you might need to do a hard refresh on the page (cmd + shift + r with a mac).  If it's still showing up as a lab, it might be a problem with the specific track you're in.  Which course are you enrolled in?

**Comment by weezwo** [comment]
I believe it is a problem with the track -- I'm enrolled in the Bootcamp Prep course.

**Comment by JessRudder** [comment]
@weezwo looks like that course was using a slightly different version of the lesson.  Now you should be all set!

**Comment by weezwo** [comment]
Looks great! Thank you!
