### ISSUE TITLE
Cloning a lab into IDE not really explicitly taught.

### ISSUE THREAD

**Issue by skmcloughlin** [learn-co-curriculum/js-jquery-modify-html-readme#8]
A tech coach showed me the information at:
http://help.learn.co/workflow-tips/github/how-to-manually-open-a-lab
and this helped immensely. Maybe 

"fork and clone this repository into your IDE."

from the instructions could be a hyperlink to these materials.

**Comment by gj** [comment]
Thanks @skmcloughlin !
