### ISSUE TITLE
Paste before </body> or </head>?

### ISSUE THREAD

**Issue by gasganno** [learn-co-curriculum/js-jquery-modify-html-readme#9]
The lesson says to paste the link to jQuery before the closing body tag. But the solution shows it pasted before the closing head tag.

Which is correct?

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
